### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by makechinafreedom** [adisreyaj/portfolio#7]
hello
 
clone , npm install , and then npm run dev

![Snipaste_2022-02-03_02-46-47](https://user-images.githubusercontent.com/83006506/152294480-57e79ce0-08be-4e08-864c-3f555baf71c9.png)
 
everything is ok....but when open http://localhost:3000/  it show me blank chrome window....
I cant find it why ..I open another project to check if it is my laptop problem, my laptop is ok..

is there any dependencies i missing to install??

**Comment by adisreyaj** [comment]
Can you check if there are any errors that you see on your browser console?

**Comment by makechinafreedom** [comment]
no errors in my browser ,,, just a blank white window, nothing show me ...

**Comment by makechinafreedom** [comment]
![Uploading Snipaste_2022-02-04_00-47-58.png…]()

**Comment by adisreyaj** [comment]
Not reproducible. Hence closing it.
